In [1]:

import numpy as np
a=np.zeros(81,dtype=int)
a.resize(9,9)   
'''
while True:
   st=input("enter row,col,value : ")
   row,col,val=[int(i) for i in st.split(",")]
   a[row-1][col-1]=val;
   br=input("continue Y or N : ")
   if br=='N' or br=='n':
     break
'''
a=np.array(([0,1,2,7,0,0,0,0,0],
            [0,7,0,6,0,8,0,0,0],
            [0,0,0,0,0,0,8,3,0],
            [0,0,8,0,0,7,0,0,0],
            [0,0,0,0,0,0,3,5,0],
            [0,0,6,0,0,4,0,0,0],
            [2,4,0,0,0,0,0,0,0],
            [0,0,0,0,5,0,0,1,6],
            [1,0,0,0,8,0,9,0,0]))

def solve():
  row=0
  col=0
  for i in range(9):
    for j in range(9):
              if i!=0 and i%3==0:
                    row=3
              if i!=0 and i%6==0:
                    row=6   
              if (j!=0 and j%3==0):
                      col+=3
              if j==0:col=0
              if a[i][j]==0:
                for k in range(1,10):
                    if  k not in a[i:i+1,:]:
                        if k not in a[:,j:j+1]:
                          if k not in a[row:row+3,col:col+3]:
                                a[i][j]=k
                                solve()
                                a[i][j]=0
                return           
  print(a)    
  x=input()
solve()

[[8 1 2 7 3 5 6 4 9]
 [9 7 3 6 4 8 1 2 5]
 [6 5 4 9 2 1 8 3 7]
 [4 3 8 5 9 7 2 6 1]
 [7 9 1 8 6 2 3 5 4]
 [5 2 6 3 1 4 7 9 8]
 [2 4 9 1 7 6 5 8 3]
 [3 8 7 2 5 9 4 1 6]
 [1 6 5 4 8 3 9 7 2]]
